<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>POSPAK's Universal Login | <?=$title?></title>
    <link rel="stylesheet" href="pulStyles.css">
</head>
<body>
    <header>
    <a href="main">
        <h1 class="mainTitle">
            POSPAK's Universal Login
        </h1>
        <h2>
            Jednotné bezpečné přihlášení
        </h2>
        <small>
            Site by POSPÁK 65
        </small>
    </a>
    </header>
    <br clear="both" />
    

<?php $this->controler->viewListing();
?>  
</body>
</html>