<!DOCTYPE html>
<html lang="cs-cz">
<head>
    <base href="/" />
    <meta charset="UTF-8" />
    <meta name="description" content="<?= $description ?>" />
        <meta name="keywords" content="<?= $keywords ?>" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="images/favicon.png" type="image/x-icon">
    <title>POSPAK's Universal Login | <?=$title?></title>
    <link rel="stylesheet" href="styles.css?v=1.1">
</head>
<body>
    <header>
    <a href="main">
        <h1 class="mainTitle">
            POSPAK's Universal Login
        </h1>
        <h3>
            Jednotné bezpečné přihlášení
        </h3>
        <small class="smallLink">
            Site by POSPÁK 65
        </small>
    </a>
    </header>
    <br clear="both" />
    
<main>
<?php $this->controler->viewListing();
?>  
</main>
<br>
<?php include 'footer.php'; ?>
</body>
</html>
