<?php
if($url == "skipaIs"){
    $url = "Škípa - Is";
}
?>

<div class="container">
<div class="column"></div>
<div class="column">
<form action="" method="post">
<h1>Přihlášení | <?=$url?></h1>
    <input type="text" name="username" id="" required placeholder="Uživatelské jméno" <?php if($url="Škípa - Is"):?>data-tippy-content="Pokud sis jméno neměnil, je nastavené na tvoji přezdívku s velkým písmenem na začátku a bez diakritiky."<?php endif;?>>
    <input type="password" name="password" id="" required placeholder="Heslo" <?php if($url="Škípa - Is"):?>data-tippy-content="Pokud se přihlašuješ poprvé, prosím obnov si heslo pomocí tlačítka níže!"<?php endif;?>>
    <input type="submit" value="Přihlásit se" name="submit">
</form>
<br><br>
<?php

if(!isset($url)||$url =="pospakTube"):
    ?>
    <p>
        Jsi tu nový? <a href="register/<?=$url?>" class="links">Zaregistruj se!</a>
    </p>
    <?php elseif($url == "Škípa - Is"): ?>
    <p>
        Zapomněl jsi heslo? <a href="https://skipa-is.skauting.cz/pass-recovery" class="links">Obnov si ho!</a>
    </p>
    <?php endif; ?>
    </div>
<div class="column"></div></div>

<script src="script.js?v=2.9"></script>
<script src="https://unpkg.com/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
    <script src="https://unpkg.com/tippy.js@6.3.1/dist/tippy-bundle.umd.min.js"></script>
<script>
  tippy('[data-tippy-content]', {
            allowHTML: true,
        });

</script>
