<h1>Přihlášení</h1>
<div class="container">
<div class="column"></div>
<div class="column">
<form action="" method="post">
    <input type="text" name="username" id="">
    <input type="password" name="password" id="">
    <input type="submit" value="Přihlásit se">
</form>
<br><br>
<?php

if(!isset($url)&& $url !="skipaIs"):
    ?>
    <p>
        Jsi tu nový? <a href="register" class="links">Zaregistruj se!</a>
    </p>
    <?php endif; ?>
    </div>
<div class="column"></div></div>