<?php
if($url == "skipaIs"){
    $url = "Škípa - Is";
}
?>
<h1>Přihlášení | <?=$url?></h1>
<div class="container">
<div class="column"></div>
<div class="column">
<form action="" method="post">
    <input type="text" name="username" id="" required>
    <input type="password" name="password" id="" required>
    <input type="submit" value="Přihlásit se" name="submit">
</form>
<br><br>
<?php

if(!isset($url) || $url !="skipaIs"):
    ?>

    
    <p>
        Jsi tu nový? <a href="register/<?=$url?>" class="links">Zaregistruj se!</a>
    </p>
    <?php endif; ?>
    </div>
<div class="column"></div></div>

<script src="script.js"></script>