
<!-- main container -->
<div class="container">
    <!-- left column -->
    <div class="column"><a href="http://pospaktube.batcave.net"><img src="back.png" data-tippy-content="Zpět na hlavní stránku" alt=""></a></div>

    <!-- middle column -->
    <div class="column">

        <div id="profile">
        <div class="container">
                <!-- left column -->
                <div class="column"></div>
                <!-- middle column -->
                <div class="column">
                    <h2><a href="change/photo"><img src="<?=$data["profilePhoto"]?>" alt="profile-img-<?=$data["username"]?>" class="profile-img-cover"></a><a href="change/username"><?=$data["username"]?></a></h2>    
                    
                    <!-- password -->
                    <a href="change/password"><img src="password.svg" height="50" width="50" alt="password-icon"><p id="passwordField">V aktuální verzi nemůžeš své heslo zobrazit. Na aktualizaci se pracuje!</p></a>
                    <!--password visibility switch -->
                    <img id="eye" alt="show-icon" onclick="togglePasswordVisibility('passwordField')" style="cursor: pointer;" width="20px" height="20px"><br>
                    
                    <!-- email -->
                    <a href="change/email"><img src="email.png" alt="email-icon" width="50" height="50"><?=$data["email"]?></a><br>
                </div>
            
                <!-- right column -->
                <div class="column"></div>

            </div>
     
            
        
        </div>
    </div>
    <!-- right column -->
    <div class="column"></div>

</div>
<script>
    
    var eye = document.getElementById("eye");
    eye.src = "show.svg";
    var field = document.getElementById("passwordField");
    field.style.display = "none";
          function togglePasswordVisibility(fieldId) {
        
        if (field.style.display === "inline-block") {
            field.style.display = "none";
            eye.src = "show.svg";
        } else {
            field.style.display = "inline-block";
            eye.src = "hide.svg";
        }
    }
        </script>
        <script src="https://unpkg.com/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
    <script src="https://unpkg.com/tippy.js@6.3.1/dist/tippy-bundle.umd.min.js"></script>
<script>
  tippy('[data-tippy-content]', {
            allowHTML: true,
        });

</script>