
<!-- main container -->
<div class="container">
    <!-- left column -->
    <div class="column">

        <div id="profile">
            <div class="container">
                <!-- left column -->
                <div class="column"></div>
                <!-- middle column -->
                <div class="column">
                    <h2><a href="change/photo"><img src="<?=$data["profilePhoto"]?>" alt="profile-img-<?=$data["username"]?>" class="profile-img"></a><a href="change/username"><?=$data["username"]?></a></h2>    
    
                </div>
            
                <!-- right column -->
                <div class="column"></div>

            </div>
        </div>
    </div>

    <!-- middle column -->
    <div class="column">

        <div id="profile">
            <!-- password -->
            <a href="change/password"><img src="password.svg" height="50" width="50" alt="password-icon"><p id="passwordField"><?=$data["password"]?></p></a>
            <!--password visibility switch -->
            <img id="eye" alt="show-icon" onclick="togglePasswordVisibility('passwordField')" style="cursor: pointer;" width="20px" height="20px"><br>
            <!-- email -->
            <a href="change/email"><img src="email.png" alt="email-icon" width="50" height="50"><?=$data["email"]?></a><br>
        
        </div>
    </div>
    <!-- right column -->
    <div class="column"></div>

</div>
<script>
    
    var eye = document.getElementById("eye");
    eye.src = "show.svg";
    var field = document.getElementById("passwordField");
    field.style.display = "none";
          function togglePasswordVisibility(fieldId) {
        
        if (field.style.display === "inline-block") {
            field.style.display = "none";
            eye.src = "show.svg";
        } else {
            field.style.display = "inline-block";
            eye.src = "hide.svg";
        }
    }
        </script>