name: Discord Notification with Commit Message

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Get commit message
        id: commit_message
        run: echo "::set-output name=message::$(git log --format=%B -n 1 $GITHUB_SHA)"

      - name: Send Discord notification
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK }}
          COMMIT_MESSAGE: ${{ steps.commit_message.outputs.message }}
        run: |
          curl -H "Content-Type: application/json" -X POST -d '{"content": "Aktualizace byla úspěšně provedena, změny by se měly projevit na webu"}' $WEBHOOK_URL
